CBIIT/crdc-datahub-validator

configs/validate-file-config.example.yml, src/common/mongo_dao.py, src/common/utils.py, src/config.py, src/data_loader.py, src/file_validator.py
1. updated to use object stream
2. updated the data_loader.py to check if a node existing if intention is "update"
3. updated the mongo_dao for intention is "update"
=> updated to use object stream

src/common/constants.py, src/common/model_store.py, src/essential_validator.py
Essential validate service were updated upon requests.  Please review.
=> Updated upon requests

requirements.txt, src/common/constants.py, src/common/error_messages.py, src/metadata_validator.py, src/test/validators/validate_required_props_test.py
1. test codes including test cases
2. required properties validator
=> CRDCDH-639

src/common/mongo_dao.py, src/common/utils.py, src/data_loader.py, src/file_validator.py, src/metadata_validator.py
1.  add new util function, current_datetime
2. replace current_datetime_str() function call with current_datetime()
3. replace import current_datetime_str with current_datetime
=> replace date string with date

src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
Create instance right before use
=> Create instance right before use

src/common/constants.py, src/common/mongo_dao.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
1.  change batch status from "Loaded" to "Uploaded"
2. change batch status from "Rejected" to "Failed"
3. update metadataValidationStatus of submission to "New" after metadata loaded to DB.
4. update metadataValidationStatus of submission to "Error" after metadata failed essential validation.
=> Crdcdh 736 001 pgu

src/essential_validator.py
Add nodeType data field in batch file object.
=> Add nodeType in batch file

configs/validate-export-config-deploy.yml, export.dockerfile
add deployment config files for export service.
=> add deployment config files

src/file_validator.py, src/service/ecs_agent.py
=> scaling in protection

src/common/constants.py, src/common/model.py, src/common/model_store.py, src/common/utils.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
1) Updated model_store.py to create different versions of model based on passed -in data common and version.
2) Update essential_validator to allow validate with different version of data model.
3) Update metadata_validator to allow validate with different version of data model.
=> Crdcdh 757 001 pgu

src/file_validator.py, src/service/ecs_agent.py
Added ECS Protection Scaling API
Deleted unused import
Deleted unnecessary lines
Renamed variables submission_id
=> ECS Protection Scaling API

src/essential_validator.py
add logics to handle no id property in metadata tsv file.
=> fix crdcdh-776

src/common/mongo_dao.py, src/essential_validator.py, src/metadata_validator.py, src/validator.py
1.  Add set_search_index() in mongo_dao.py that sets search parents index, "submissionID_nodeType_nodeID" in dataRecords collection.
2. Add search_nodes_by_index() in mongo_dao.py that search parents by index, "submissionID_nodeType_nodeID".
3. Add get_dataRecords_chunk()  in mongo_dao.py that retrieved data by chunk by chunk, chunk size is set to 10k.
4. updated validator.py to set the search index if no index set before service starting.
5. update metadata-validator.py to validate data chunk by chunk.
6. updated essential_validator.py to add null handler for node without id property.
=> Crdcdh 778 001 pgu

src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
Fix tsv file with empty header issue
=> implemented changes

src/common/model.py, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py
fixed issues: crdcdh 794 and 800
=> Crdcdh 800 002 pgu

src/common/mongo_dao.py, src/essential_validator.py, src/metadata_validator.py
Fix crcdch-805 and updated metadata validator to fix a unreported bug.
=> Crdcdh 805

src/common/constants.py, src/common/mongo_dao.py, src/file_validator.py, src/metadata_export.py
1.  updated metadata_export.py to add logics to add records in crdcIDs collection.
2. updated mongo_dao.py to add couple of new functions to get and insert record in the collection crdcIDs.
3. update constants.py to add related constants.
=> Implemented requirements

src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/metadata_export.py, src/validator.py
1) mongo_dao.py:  add set_search_index_crdcIDs, search_crdc_record functions, updated get_crdc_record by remove a parameter, submisionID 
2) updated validator.py to add search index for crdcIDs before services start.
3) updated data_loader.py for get or create crdc_id, updated the construct by adding one data_common parameter.
4) minor updated metadata_validator to call data_loader by passing dat_common.
5) minor update metadata_export.py when call get_crdc_record by only passing crdc_id.
=> Crdcdh-832

src/metadata_validator.py
crdcID search after parent relathionship node fails.
=> CRDCDH-845

src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
=> Crdcdh 818 001 pgu

src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
=> updated messages

src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py
1) Fixed crdcdh-818
2) Make fix for crdcdh-862 works for both new, update and delete.
3) Make update_data_records return true if no exceptions that will make it return true for upsert.
=> Fixed crdcdh-818

src/data_loader.py, src/essential_validator.py
stripe white spaces in tsv column names
=> stripe white spaces in tsv column

src/common/mongo_dao.py, src/data_loader.py, src/metadata_validator.py, src/validator.py
1) implemented new requirement in the ticket.
2) change line #
=> implemented new requirement

src/metadata_validator.py
1) updated the related message in the format as listed below:
title: "Related node not found"
description: "Related node “study” [“phs_accession”: “CDS-CASE-343844"] not found."
2) cleanup redundant code.
=> Updated related error message

configs/validate-export-config-deploy.yml, configs/validate-export-config.example.yml, s3_download/readme, src/common/mongo_dao.py, src/metadata_export.py, src/validator.py
1.  Rewrite the export service
2. add new function in mongo_dao.
=> Headers issue in released  metadata

src/common/constants.py, src/common/model_reader.py, src/common/mongo_dao.py, src/data_loader.py, src/metadata_export.py, src/metadata_validator.py, src/validator.py
1) implemented requirements for crdcdh-884 upsert submission.
2) updated model readrer for value list type and multiple relationships
3) updated matedata validation for value list.
=> implemented 884

src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
1) add find last batch by fileName function in mongo_dao.py 
2) updated file_validator.py to rewrite the extra file error based on requirements in the ticket.
3) update data_loader.py to convert nan to None in dataframe to avoid issues in metadata validation.
4) add node type validation in essential_validator.py
=> Implemented crdcdh-903

src/common/model_reader.py, src/data_loader.py, src/essential_validator.py, src/metadata_validator.py
1) CRDCDH-889
2) CRDCDH-916
3) CRDCDH-917
4) CRDCDH-919
5) CRDCDH-930
6) CRDCDH-938
7) CRDCDH-940
=> Fix validation issues

src/metadata_validator.py
1) fix missing quote.
2) allow number for a string type.
=> Fix issues in dev

src/file_validator.py
Allow file validation without manifest.
=> Remove block of no manifest

src/essential_validator.py
=> Fix file not found issue

src/common/mongo_dao.py
=> Crdcdh 964 002 pgu

src/essential_validator.py
Updated essential_validator.py to fix crdcdh-965 and 963.
=> Fixed 965 and 963

src/essential_validator.py, src/metadata_validator.py
1. Implemented crdcdh-972
2. fixed crdcdh-966
3. fixed crdcdh-967
=> Implemented crdcdh-972

src/common/constants.py, src/common/mongo_dao.py, src/metadata_validator.py
Updated metadata_validator, mongo_dao and constants.
=> Fix 980 and 981

src/common/mongo_dao.py, src/essential_validator.py
1.  Fixed crdcdh-991 by updated essential validation function.
2. Fixed crdcdh-992 by updated essential validation function and added/modified mongo_dao.
3. Fixed reopend-965 by differential error message for missing single and multiple required properties. 
4. Fixed reopend-962 by setting node type in file object.
=> Fixed bugs.

src/essential_validator.py
=> Updated teh message.

src/file_validator.py
Updated file_validator.py for reset validation errors and warnings.
=> Reset File errors

src/common/mongo_dao.py, src/file_validator.py
Updated the set submission status function in mongo_dao.py
=> Update set submission function

src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_export.py, src/metadata_validator.py
1.  Implemented crdcdh-1040
2. Enhanced concurrent updating on dataRecords by validators.
=> Implemented crdcdh-1040

src/common/mongo_dao.py
1) modified set_submission_status function in mongo_dao.py to resolve overall metadataValidationStatus.  Please note fileValidationStatus is the overall status already.
=> Fixed crdcdh-1049

src/file_validator.py
otherwise it will cause GraphQL type errors.
=> Changed default displayID to null

src/common/mongo_dao.py, src/essential_validator.py
1) implemented new logics for 1052 in essential_validator.py.
2) updated check_metadata_ids fuc=nction in mongo)dao.py.
=> Crdcdh 1052

src/common/constants.py, src/common/model.py, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
1.  implemented crdcdh-983 and 984.
2. updated crdc_id search logic to exclude deleted release record.
=> Crdcdh 983 and 984

src/common/constants.py, src/common/model.py, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_export.py, src/metadata_validator.py
=> Implemented Crdcdh 987

src/common/constants.py, src/common/model.py, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_export.py, src/metadata_validator.py, src/x_submission_validator.py
1) add new class, x_submission_validator.py
2) updated metadata_vlidator.py to use the new class.
2) add new DAO functions for check cross-submission in mongo_dao.py
3) updated a common DAO function, set_submission_status to take new parameter, cross_submission_status.
4) update the common DAO function caller for the new parameters in all validators.
=> Implemented crdcdh-995

src/metadata_validator.py
Update the metadata_validator.py
=> Fixed an error is not added issue 

src/essential_validator.py
Updated essential_validator.py to add line number to error message in different cases as listed below:
1) rows missing Key property value.
2) duplicated rows.
3) existed records rows for "New".
4) no records existed rows for "Delete".
5) rows with invalid m2m relationships.
=> Implemented Crdcdh 968

src/essential_validator.py
updated the check_m2m_relationship function in essential_validator.py
=> fixed 1065

src/file_validator.py
Updated file_validator.py to fixed the issue.
=> Fixed 1067

src/common/constants.py, src/common/mongo_dao.py, src/metadata_validator.py
=> Implement CRDCDH-1074

src/metadata_export.py
remove the save_release statement by merging codes
=> Updated to correct merge issue

src/common/model_reader.py, src/common/model_store.py, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_export.py, src/metadata_validator.py, src/service/ecs_agent.py, src/validator.py, src/x_submission_validator.py
convert log.debug to log.exception when exception occurred.
=> Implemented crdcdh-1103

src/file_validator.py
=> Implemented crdcdh-1109

src/common/constants.py
Implemented CRDCDH-1100 for MVP and passed all necessary testing.
=> Implemented CRDCDH-1100 for MVP

src/common/model_reader.py, src/common/model_store.py, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/file_validator.py, src/metadata_export.py, src/metadata_validator.py, src/service/ecs_agent.py, src/validator.py
=> Enable log

src/common/constants.py, src/common/model.py, src/common/model_reader.py, src/common/model_store.py, src/metadata_validator.py
=> Implemented crdcdh-1136

src/common/model_reader.py
implemented 1161 in PMVP by updated model reader
=> implemented 1161 in PMVP

src/common/constants.py, src/common/model.py, src/common/model_reader.py, src/common/model_store.py, src/file_validator.py, src/metadata_validator.py
1) Fixed crdcdh-981 and 975 for message updating.
2) implemented 1161 and 1136
=> Fixed 981 and 975

src/common/utils.py, src/data_loader.py, src/essential_validator.py
1.  implemented crdcdh-1177.
2. fixed bugs: 1143 and 1142
=> Implemented 1177

src/common/mongo_dao.py, src/common/utils.py, src/essential_validator.py
=> fixed 1154

src/essential_validator.py, src/metadata_validator.py
Updated the message with final version of message.
=> Fixed 1036

src/essential_validator.py
Updated based on modified requirement.
=> Updated based new requirement in Crdcdh 1177 

src/essential_validator.py
Fixed duplicated erros for metadata with duplicated rows issue.
=> Crdcdh 968 duplicate errors

src/essential_validator.py
1.  Add line number to error message.
2. Implemented newest requirements in 1105
=> Add line number to error message

src/metadata_export.py
=> fixed 1221 and 1239

src/common/constants.py, src/common/mongo_dao.py, src/essential_validator.py, src/file_validator.py, src/metadata_validator.py
Implemented 1233 and passed testing
=> Implemented 1233

README.md, src/common/mongo_dao.py, src/file_validator.py, src/metadata_export.py, src/metadata_validator.py
Update the readme.md and all messages contain "file" to "data file".
=> Updated data file

src/common/mongo_dao.py, src/essential_validator.py, src/metadata_validator.py, src/x_submission_validator.py
1) implemented crdcdh-1267.
2) enhanced essential validation for "Delete" submission by check key prop/val and file_name prop/val.
=> Crdcdh 1267

src/metadata_validator.py
manually merged codes from the branch to 2.0.0
=> merge codes

src/common/mongo_dao.py, src/data_loader.py, src/x_submission_validator.py
=> undo update node status.

src/common/model_store.py
Added exception handler for model reader.
=> Hotfix CTDC model reader exception

src/common/mongo_dao.py, src/essential_validator.py
Added update submission validation status logics
=> Crdcdh 1284

src/common/constants.py, src/dcf_manifest_generator.py
implemented the logic to check if the id contains the prefix, if not add the prefix.
=> Add prefix for dcf manifest

src/x_submission_validator.py
=> Change conflict sub ids to array

src/metadata_export.py
remove last "/" in  subfolder for DataSync.
=> hotfix for subfolder with "/"

src/dcf_manifest_generator.py
=> implemented

src/metadata_export.py
Add thread to monitor dataSync
=> Add thread to monitor dataSync

src/dcf_manifest_generator.py, src/metadata_export.py
implemented 1492 and 1493 and passed testing.
=> implemented 1492 and 1493

src/data_loader.py
generate file CRDC IDs base on file iDs
=> CRDCDH-1494

src/essential_validator.py
=> fix crdcdh-1557

src/data_loader.py
=> latestBatchDisplayID

src/common/utils.py, src/metadata_export.py
combine parents in release record.
=> combine parents

src/metadata_export.py
=> Crdcdh 1550 001 pgu

src/essential_validator.py
=> fixed issue

src/common/mongo_dao.py, src/file_validator.py
Implemented new deign to set fileValidationStatus to null if no file nodes.
=> implemented the new design.

src/common/mongo_dao.py, src/common/utils.py, src/essential_validator.py, src/file_validator.py, src/metadata_export.py
1. Implemented CRDCDH 1620 for adding tags to DataSync tasks. 
2. Merge fixes in 2.0.0 to 3.1.0
=> Crdcdh 1620

src/common/constants.py, src/common/model.py, src/data_loader.py, src/metadata_export.py
Updated following files:
1.  model.py,  add getEntityType function.
2. data_loader.py, add entityType property for upserting node record.
3. metadata_export, add entityType property for add/update release record.
=> Crdcdh 1679

src/common/pv_term_reader.py
Pull all CDE with origin of caDSR
=> Pull all CDE

src/metadata_export.py
Updated to wait 5 min before delete Datasync task and locations.
=> updated for new design.

src/metadata_export.py
=> CRDCDH-1784

src/metadata_export.py
fixed issues after remove crdc_id for non-main nodeType.
=> Crdcdh 1722

src/common/mongo_dao.py, src/pv_puller.py
=> fix duplicate issue.

src/metadata_validator.py
=> fixed duplicated cde when validating

src/metadata_validator.py
Pass validation if CDE PV list is null or empty
=> pass validation if PV is null or empty

src/essential_validator.py
fixed the issue by set the dataDeleted to false.
=> Hot fix to set dafaDeleted to false

src/metadata_validator.py
fine tune the logic to different list is none and []
=> fix empty PV issue.

src/data_loader.py, src/metadata_export.py
implemented CRDCDH-1754 and passed test in local.
=> CRDCDH-1754

src/common/model_store.py, src/common/pv_term_reader.py, src/pv_puller.py
Updated based on structure changes in content.json file:
1.  Model reader.
2. Term reader for pv puller.
=> CRDCDH 1724

src/common/constants.py, src/metadata_export.py
Implemented to updated exporter by add history in release doc.
=> CRDCDH-1716

src/file_validator.py, src/metadata_validator.py
=> Crdcdh 1687

src/metadata_validator.py
=> Hotfix1687 3

mongo_db_script/updateDataRecordsScript.js, mongo_db_script/updateReleaseScript.js, src/common/mongo_dao.py, src/validator.py
1.  updated search function for get existing crdc_id.
2. updated the DAO to generate new index in dataRecords, studyID_entityType_nodeID.
3. created a js script to populate studyID in dataRecords, it can run in mongoDB shell.
4. created another js script to populate studyID and entityType for release collection
=> Crdcdh 1891

src/metadata_validator.py
Enhanced logics to handle the case without any csDSR terms.
=> CRDCDH 2015

src/common/constants.py, src/common/mongo_dao.py, src/metadata_validator.py
Implemented based on synonym collection in database.
=> CRDCDH-2106

src/config.py
Updated constant for dataSync role.
=> Updated constant for dataSync role.

src/metadata_validator.py
Find Internal error occurred when check synonym and fixed by minor change
=> Hot fix on synonym

configs/messages_configuration.yml
Updated message by suffix a period "." if not there.
=> Crdcdh 2106 002

src/replae-file-id.py
The purpose of this script is finding all files within a data submission that don't have correct file_ids and replace the file_ids and crdc_ids with correct DRS IDs
=> Crdcdh 2303 file id replacer

src/common/api_client.py, src/pv_puller.py
Keep the original value type for CDE code and version.
converted to string when construct search url of caDSF dynamically.
=> CRDCDH 2256

mongo_db_script/restoreErrorCodeInQCResults.js
Developed a mongoDB script, restoreEooroCodeInQCResults under folder mongo_db_script.
=> Implemented CRDCDH-2243

mongo_db_script/restoreUserStudyID.js
Created a mongo DB script, restoreUserStudyID.js, under mongo_db_script folder.  
The function in the script: 1) find user records with studies but without studies._id. 2) converter string array to object array.
=> CRDCDG-2310

mongo_db_script/restoreApplicationVersion.js
Created a DB script, restoreApplicationVersion.js,  to restore application.version based on application.status under mongo_db_script/
=> CRDCDH 2309

mongo_db_script/restoreErrorCodeInQCResults.js
Remove a duplicated line in the DB srcipt.
=> Remove duplicate line.

src/metadata_export.py
Optimized the codes to prevent split a none value.
=> CRDCDH 2252

src/dcf_manifest_generator.py
Fixed the split issue in DCF generator.
=> fix the split issue.

src/data_loader.py
Found the root cause and fixed the issue by minor change.
=> fixed no "index" column in rawData issue.

configs/messages_configuration.yml, src/metadata_validator.py, src/pv_puller.py
Implemented CRDCDH-2370.
1) updated the pv_puller.py by adding a new function, get_pv_by_datacommon_version_cde
2) updated metadata_validator.py to use the 1) for dynamic CDE/pv-list retrieving.
=> Crdcdh 2370

mongo_db_script/restoreErrorCodeInQCResults.js
add one mapping,  "Duplicated data file content detected": "F007",
=> hot fix error code

configs/messages_configuration.yml, src/metadata_validator.py
Fixed the issues found in DEV by Sumologic
=> Hotfix issue in dev

configs/messages_configuration.yml, mongo_db_script/restoreErrorCodeInQCResults.js
updated 1) messages_configuration.yml.  2) restoreErrorCodeInQCResults.js in 3.2.0
=> updated error code and message

mongo_db_script/restoreErrorCodeInQCResults.js
updated mongo_db_script/restoreErrorCodeInQCResults.js to add map for "Data file records not found": "F002".
=> update error title

src/metadata_validator.py
=> fixed CRDCDH-2479

essentialvalidation.dockerfile, export.dockerfile, filevalidation.dockerfile, metadatavalidation.dockerfile, pv_puller.dockerfile
Upgrade the python version to 3.12.9-alpine3.21 in all docker files.
=> Upgrade Python

src/metadata_export.py
=> CRDCDH-24295

configs/messages_configuration.yml, src/metadata_validator.py
Updated error messages based on the changes in the US 2326
=> Crdcdh 2326

mongo_db_script/restore_data_file_location.js, src/common/constants.py, src/metadata_export.py
Implemented Crdcdh 2496.
1) updated metadata_expoter.py.
2) add a restore Db script, restore_data_file_location.js
=> Crdcdh 2496

configs/messages_configuration.yml, src/common/constants.py, src/common/model_reader.py, src/metadata_validator.py
Implemented Crdcdh 2514.
1) updated model_reader to add pattern.
2) updated metadata_validator to validate property value by patter if the property has pattern in data model.
=> Crdcdh 2514

configs/messages_configuration.yml, src/common/mongo_dao.py, src/data_loader.py, src/essential_validator.py, src/metadata_validator.py
Add invalid value in the message.
=> Add invalid value in the message.

configs/messages_configuration.yml, src/metadata_validator.py
Added new error message, M032,  if the pattern in model is invalid.
=> Crdcdh 2592

src/metadata_export.py
Convert submission.createAt to str.
=> convert submission.createAt to str

src/metadata_export.py
=> Hot fix complete submission

src/metadata_export.py
Update the release manifest.json
=> Update the release manifest

essentialvalidation.dockerfile, export.dockerfile, filevalidation.dockerfile, metadatavalidation.dockerfile, pv_puller.dockerfile
=> upgrade python to 3.12.10

configs/messages_configuration.yml, src/common/constants.py, src/common/mongo_dao.py, src/metadata_validator.py
Implemented as listed below:
1) created a function to compare new node with existing node.
2) check different by calling the function, if no diff, no warning
3) add new error message M033, check if requires property value.  if is delete command, raise error of M033.
=> Crdcdh 2717

src/essential_validator.py
Fixed CRDCDH-2766 b7y updated error message.
=> Updated the error message

src/common/constants.py, src/common/model.py, src/common/model_reader.py, src/data_loader.py, src/essential_validator.py
Implemented CRDCDH 2708 with composition ID inserting features.
=> Crdcdh 2708

src/common/mongo_dao.py, src/metadata_export.py, src/metadata_validator.py
=> CRDCDH-2712

src/common/model_store.py, src/essential_validator.py, src/metadata_export.py, src/metadata_validator.py
=> Crdcdh 2843

src/common/mongo_dao.py
Reverts CBIIT/crdc-datahub-validator#276
=> Revert "CRDCDH-2709"

src/common/mongo_dao.py, src/metadata_validator.py, src/pv_puller.py
Add CDE code to pvConceptCode Mapping.
=> Add CDE code to pvConceptCode Mapping.

src/common/constants.py, src/common/model_reader.py
=> CRDCDH 2631

src/data_loader.py
=> CRDCDH 2866

src/essential_validator.py
=> CRDCDH-2907

src/metadata_validator.py
Enhanced concept generator for list values
=> Enhanced concept generator for list values

src/metadata_export.py
Minor change by remove "," after a statement to fixed the issue.
=> Fixed 2953

src/metadata_validator.py
Fixed the logic to display the error.
=> correct the condition for the error

src/data_loader.py
Fix CRDSDH 2972 by updated the counts.
=> CRDSDH 2972

src/common/mongo_dao.py, src/file_validator.py, src/metadata_validator.py
Make validationEnded property in the submission collection only updated when both validation finished
=> CRDCDH 2637

src/metadata_remover.py
Update to remove node_type check for metadata deletion
=> CRDCDH-3285
